FROM rocker/r-ver:4.0.0


COPY scripts /shell_scripts
RUN chmod -R +x /shell_scripts


RUN /shell_scripts/install_sys_deps.sh


ENV JULIA_PATH /usr/local/julia
ENV PATH $JULIA_PATH/bin:$PATH
RUN /shell_scripts/install_julia.sh

RUN /rocker_scripts/install_tidyverse.sh
RUN /rocker_scripts/install_python.sh




RUN /shell_scripts/install_mssql_driver.sh


RUN Rscript /rocker_scripts/install_basic_r_pkgs.R

## run R plumber with the last supplied CMD as supplied file
ENTRYPOINT ["R", "-e", "pr <- plumber::plumb(rev(commandArgs())[1]); pr$run(host='0.0.0.0', port=8000, swagger=TRUE)"]