FROM apache/airflow:2.1.3-python3.8

USER root

# keep group id same as host
RUN groupadd --gid 119 docker \
    && usermod -aG docker airflow \
    # fix jdk https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    && mkdir -p /usr/share/man/man1 \
    && cd / \
    && mkdir -p /tmp \
    && apt-get update \
    && apt-get install -y pandoc g++

COPY scripts /shell_scripts
RUN chmod -R +rx /shell_scripts

RUN /shell_scripts/install_r.sh

RUN /shell_scripts/install_sys_deps.sh
RUN R CMD javareconf

RUN /shell_scripts/install_mssql_driver.sh


RUN pip3 install --default-timeout=100 -I -r /shell_scripts/requirements_airflow_v2.txt
RUN pip uninstall --yes azure-storage && pip install -U azure-storage-blob apache-airflow-providers-microsoft-azure==1.1.0


# ENV JULIA_PATH /usr/local/julia
# ENV PATH $JULIA_PATH/bin:$PATH
# RUN /shell_scripts/install_julia.sh


RUN Rscript /shell_scripts/install_basic_r_pkgs.R

USER airflow
