FROM rocker/shiny-verse:4.0.0


COPY scripts /shell_scripts
RUN chmod -R +x /shell_scripts


RUN /shell_scripts/install_mssql_driver.sh
RUN Rscript /rocker_scripts/install_basic_r_pkgs.R


RUN /rocker_scripts/install_tidyverse.sh