FROM puckel/docker-airflow:1.10.9

USER root

RUN groupadd --gid 119 docker \
    && usermod -aG docker airflow \
    # fix jdk https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
    && mkdir -p /usr/share/man/man1 \
    && cd / \
    && mkdir -p /tmp

COPY scripts /shell_scripts
RUN chmod -R +rx /shell_scripts

RUN /shell_scripts/install_r.sh

RUN /shell_scripts/install_sys_deps.sh
RUN /shell_scripts/install_mssql_driver.sh


RUN pip3 install -r /shell_scripts/requirements_airflow.txt


ENV JULIA_PATH /usr/local/julia
ENV PATH $JULIA_PATH/bin:$PATH
RUN /shell_scripts/install_julia.sh


RUN Rscript /shell_scripts/install_basic_r_pkgs.R

USER airflow